export const env = {
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    PAPAREO_API_KEY: process.env.PAPAREO_API_KEY,
    HF_TOKEN_KINGSLEYENG: process.env.HF_TOKEN_KINGSLEYENG,
    HF_TOKEN_KJDON_WMAI_RESEARCH: process.env.HF_TOKEN_KJDON_WMAI_RESEARCH,
    PUWHAKAHUA_API_KEY: process.env.PUWHAKAHUA_API_KEY,
};
